import XCTest
@testable import RestoreEngine

/// Parity gates for the classical stages: Swift output must match the Python CLI's output
/// for the same isolated operation. Fixtures were generated by the reference CLI:
///   contrast: `restore-photos input -o contrast.png --no-face --scale same`
///   resize:   `restore-photos input -o resize.png   --no-face --no-contrast --size 400x`
/// Compared via mean-SSIM on luminance. Thresholds account for ImageIO-vs-PIL decode and
/// CILanczos-vs-PIL-Lanczos kernel differences (bit-exact parity isn't expected).
final class ParityTests: XCTestCase {

    private func fixture(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(
            Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "Fixtures"),
            "missing fixture \(name).\(ext)"
        )
    }

    func testContrastMatchesReference() throws {
        let input = try ImageLoading.load(url: fixture("input_77ish", "jpeg")).image
        let swiftOut = Contrast.normalize(input)
        let reference = try ImageLoading.load(url: fixture("contrast_77ish", "png")).image

        XCTAssertEqual(swiftOut.width, reference.width)
        XCTAssertEqual(swiftOut.height, reference.height)

        let ssim = Metrics.ssim(swiftOut, reference)
        let psnr = Metrics.psnr(swiftOut, reference)
        print("contrast parity: SSIM=\(ssim) PSNR=\(psnr)dB")
        XCTAssertGreaterThanOrEqual(ssim, 0.97, "contrast SSIM \(ssim) below gate")
    }

    func testResizeMatchesReference() throws {
        let input = try ImageLoading.load(url: fixture("input_77ish", "jpeg")).image
        let target = try Resolution.parseSize("400x")
        let (tw, th) = try Resolution.resolveDimensions(target, origW: input.width, origH: input.height)
        let swiftOut = Lanczos.resize(input, toWidth: tw, toHeight: th)
        let reference = try ImageLoading.load(url: fixture("resize_77ish", "png")).image

        XCTAssertEqual(swiftOut.width, reference.width, "target width mismatch")
        XCTAssertEqual(swiftOut.height, reference.height, "target height mismatch")

        let ssim = Metrics.ssim(swiftOut, reference)
        let psnr = Metrics.psnr(swiftOut, reference)
        print("resize parity: SSIM=\(ssim) PSNR=\(psnr)dB")
        XCTAssertGreaterThanOrEqual(ssim, 0.95, "resize SSIM \(ssim) below gate")
    }
}
